### ISSUE TITLE
Wrong icon for popout editor button

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#1026]
### Describe the Bug

Properties panel popout editor is wrong

![image](https://github.com/bpmn-io/form-js/assets/1022916/4fc0ddaa-b044-4817-ba8f-bfaff08b67b5)

### Steps to Reproduce

1. Hover over any entry that has a popout editor in the properties panel
2. The icon is wrong
3. now this happens

### Expected Behavior

The icon should be right

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by douglasbouttell-camunda** [comment]
properties-panel was fixed in https://github.com/bpmn-io/properties-panel/commit/e43101fcbcee7d91479efde8e9bf59e545ff33c5 (v3.20.1)

form-js was updated in https://github.com/bpmn-io/form-js/commit/6543d84a02381e5d06708d55de75188bfcb9cbd9 (v1.8.8) to use properties-panel 3.20.x

Once form-js is released this should be fixed.

**Comment by Skaiir** [comment]
Ah actually I simply missed this issue, but it was fixed via https://github.com/bpmn-io/form-js/commit/43c5615e94d23b2ad61bc7f858f28a3988214bfa and released already in 1.8.8 and 1.9
