### ISSUE TITLE
Remove validation delay

### ISSUE THREAD

**Issue by bilalmalkoc** [bpmn-io/form-js#1127]
### Describe the Bug

Hello. Is possible to delete form validation delay? When change required input fields, validation process works late.

### Steps to Reproduce

1. Create a form with required fields.
2. Display with form-viewer.
3. Trigger required fields.

### Expected Behavior

I think validation message and colored border must appear instantly.

### Environment

- Google Chrome Version 123.0.6312.107
- OS: macOS Sonoma 14.4.1 
- Library version: 1.8.3

Demo:

https://github.com/bpmn-io/form-js/assets/23140025/c1c71598-752a-4c6b-b8ae-966e68e9f6bf

**Comment by Skaiir** [comment]
@bilalmalkoc This is due to debouncing and expected behavior more or less. I guess the fact that it's not perfectly consistent across components is something we should improve, but yeah we more or less want this so that we don't display changing errors constantly as users are entering their data. 

You can disable debouncing via config, but it will affect performance for really big forms.

**Comment by bilalmalkoc** [comment]
@Skaiir won't use big forms. i can not find any detail to disable debouncing in the docs.

**Comment by Skaiir** [comment]
@bilalmalkoc Fair point, I'll add a task to document the API a little more after. 

But this should work:

```js
const form = new Form({
  container: document.querySelector('#form'),
  debounce: false
});
```
