### ISSUE TITLE
One error when i use Form

### ISSUE THREAD

**Issue by una33-unn** [bpmn-io/form-js#1128]
import { Form } from '@bpmn-io/form-js-viewer';
THEN
<img width="658" alt="1712568197028" src="https://github.com/bpmn-io/form-js/assets/165490816/606bde98-97d8-40e0-9b80-82653b68ec52">

**Comment by Skaiir** [comment]
Hey @una33-unn,

I'm closing the issue due to lack of detail, please follow our [issue template](https://github.com/bpmn-io/form-js/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.md) and provide some further information so we can investigate. 

Information that would be useful: What kind of project is this being built in. Are you doing something special with Webpack? Ect...
