### ISSUE TITLE
Open Links in New Tab by Default

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#116]
### Is your feature request related to a problem? Please describe

When using links in the markdown/HTML form field the linked documents open inside the same tab unless `target="_blank"` is added manually.

![aQD4CrOEby](https://user-images.githubusercontent.com/7633572/123630612-0635c780-d816-11eb-9bcf-f7f30f7d3840.gif)

This behavior might be unexpected from the user's point of view.

### Describe the solution you'd like

A potential fix would be to add `target="_blank"` by default.

### Describe alternatives you've considered

Doing nothing and leaving the decision to the developer integrating the library. (cf. https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)

### Additional context

Follow-up to https://github.com/bpmn-io/form-js/issues/101

**Comment by nikku** [comment]
Can we make this a proper enhancement request. 

I'd love to add alternative behavior I'd consider. Given that integrators can already intercept page navigation (and cancel it, cf. screen cast) doing nothing at all is a fine solution, too. Especially because it is good practice to not forcefully open links externally, too.

**Comment by philippfromme** [comment]
Okay, will add the alternative. I had already added the _needs discussion_ label to indicate that this needs further discussion.

**Comment by philippfromme** [comment]
@nikku I've updated the isse.

**Comment by andreasgeier** [comment]
I'm in favor of a new tab as I already mentioned in this [issue](https://github.com/bpmn-io/form-js/issues/101#issuecomment-869474802). Staying on the page is possibly destructive. Also, the use cases I can imagine (open docs, check other systems, additional information, etc.) are speaking for a new tab solution.

**Comment by nikku** [comment]
It is trivial for library integrators to hook into the navigation and prevent it. In fact that is what we already do on our demo as well as in the Camunda Modeler.

Building a library we must assume that integrators know what they are doing (to some extend). Maybe we can make the behavior configurable one day, however let us not force this behavior upon our users.

**Comment by nikku** [comment]
On a related note it should be possible to manually add your own `<a target="_blank">` links into the template if you wish to. That is not the case, as we're running into [an upstream bug](https://github.com/developit/snarkdown/issues/98). If we had it, people could always add `<a target="_blank">` links to overrule good web practices.

**Comment by nikku** [comment]
Users will be able to assert full control over their link open behavior once https://github.com/bpmn-io/form-js/pull/121 is merged.

**Comment by nikku** [comment]
Given the mixed opinions on this one and existing workarounds in place, let's close this one and await further feedback.

**Comment by korthout** [comment]
I've encountered a need for this as well. 

We use Tasklist in the release process of Zeebe with extensive Forms usage. Many of the forms use Markdown formatted text often with links. As far as I've seen, these links won't ever refer to Tasklist, they are always external. Leaving Tasklist when clicking these links is kinda annoying, because you click the link to learn more about how to complete this task. Then once you know, you generally want to return to Tasklist to complete the task. Which means finding it in your browser history.

I understand I focus here on Tasklist, and I don't know the full extent of other use cases for the forms, but in my opinion it makes a lot of sense to open the rendered markdown links in a new tab. Or make this configurable, so a tool like Tasklist can enable it.

**Comment by christian-konrad** [comment]
Let's fix this now, it is pending for a while and quite a problem. @marcosgvieira

**Comment by Skaiir** [comment]
We want this definitely, but we don't want to modify existing behavior, so I'm implementing a new flag for library consumers.
