### ISSUE TITLE
Support multi-select checkbox

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/form-js#196]
__Is your feature request related to a problem? Please describe__

As a form design I can model a component which can have `n` options, where the later form-user is able to select `m` (`0<=m<=n`) entries. On submission, the `m` selected options are submitted as list.

__Describe the solution you'd like__

Compare to:
* Radio Button component, but with the ability to select multiple entries (as form user)
* see form.io [`Select Boxes` component](https://help.form.io/userguide/forms/form-components#select-boxes)

![image](https://user-images.githubusercontent.com/9433996/162966132-906e2a63-e9c5-4901-a088-88859c675bcf.png)

__Describe alternatives you've considered__

n/a

__Additional context__

Raised as part of https://jira.camunda.com/browse/SUPPORT-12025 interaction
Child of https://github.com/bpmn-io/form-js/issues/200

**Comment by pinussilvestrus** [comment]
Note that providing data for such a form field also touches the problem [described in this comment](https://github.com/bpmn-io/form-js/issues/200#issuecomment-964024382) (selected values are an array/list).

**Comment by andreasgeier** [comment]
I'm not sure whether the difference between `Checkbox` and `Select boxes` are clear to the user. 

First, it results in different JSON output (without showing the output in our editor, how would the user know?). 
Second, from the UI perspective is a single checkbox just a group of one (probably without group title).

I saw that form.io makes this difference but I don't understand the why.

**Comment by pinussilvestrus** [comment]
> without showing the output in our editor, how would the user know?

That's also a good indicator for having a preview function (e.g. the playground). I see it also as a part of the overall story (https://github.com/bpmn-io/form-js/issues/200).

**Comment by Skaiir** [comment]
@andreasgeier When you say user you mean the forms developer not the tasklist operator right?

**Comment by Skaiir** [comment]
@andreasgeier 

With regards to the first point, that's only specific to this case right now, but in the future it will apply to any kind of more complex field we might want. Right now we've been relying on the fact that the fields we offer are only really obvious one to one mappings, but if we wanted something like datetime it's the same problem, how do we know what format we use to store this? It's complete guesswork on the developer's side or they have to rely on documentation (which I don't think we have) or inspect the sent JSON, but we could just show them, hence massive +1 to @pinussilvestrus 's comment, which would solve the functional differentiation problem,

With regards to the UI point, I'm not sure that's a problem. If we're talking about the forms editor it's pretty clearly differentiated via selection:

![image](https://user-images.githubusercontent.com/17801113/164481550-8c18bee5-61d8-4550-9210-7f5673f43c0a.png)

If we're talking about the display side (ie Tasklist), I think that's also fine. The person receiving the forms shouldn't really know about internals, ultimately the separation only exists for the sake of the process developer, if it looks the same or not on the front end shouldn't be a problem. 

The alternative of keeping them as a single component is a bit dodgy in my view because then we have one component which can be written in two formats. We also then need a few configuration fields on that component like (is multi checkbox) and (is dynamically loaded), which add a (I admit not huge) layer of having to dig through configuration to get the expected behavior.

Now we could argue that on its own the multi checkbox isn't that useful, you could replace it practically by multiple individual checkboxes, I agree wholly. But since we're trying to add in dynamic values, loaded in from the inputs, we need a component capable of hosting multiple values. 

There are also some mild differences in visuals, the new multiselect checkboxes would be more compact as they create a group together. (ignore the input data)

![image](https://user-images.githubusercontent.com/17801113/164487185-879dfead-1173-4d86-8961-f374e39f78e7.png)

**Comment by andreasgeier** [comment]
> The alternative of keeping them as a single component is a bit dodgy [...] Now we could argue that on its own the multi checkbox isn't that useful, you could replace it practically by multiple individual checkboxes

I agree that a single checkbox shouldn't be misused to create a group, the interaction would be cumbersome. My thought went in the opposite direction: just providing the `checkbox group` component. In my view, a single checkbox can be modeled with a checkbox group: one item, group title optional.

In the form editor, I can model a `select` or a `radio group` with just one entry (likely not reasonable but possible). In case of a `checkbox group`, a single entry would be a valid case and it would be just the same like `select` and `radio`.

Still, these thoughts are coming from the question why we need a specific `1` case if we support a `n` case (including 1).

**Comment by Skaiir** [comment]
Because the `1` case and the `n` case are structured differently in the underlying data. I've modeled both in the above forms editor. Hosting within a multi-select creates a level of nesting no matter what and this we cannot get around. If we make singular checkboxes follow the same pattern, well first this will require a migration step for users, and secondly it won't be as nice:

If you have a singular checkbox that maps a boolean `variable`, you can check this with a simple `if (data.variable)`
If you have a multi checkbox of size `1`, mapping to an array of strings `variables`, 
the condition becomes `if (data.variables.contains(variable))` 

I think the point is that these are two different components functionally and in their application. 

- A list of checkboxes models a list of selections and I would even be for the idea of it not using checkboxes at all but some other type of control. We're trying to implement multiselects, the fact that we display it as checkboxes is just convenient because it's easy to do and usable. But conceptually what we want out of them is an array of values. 
- A singular checkbox implies some kind of logical branching, did you accept the terms and condition, should you append X to Y, ect ect. 

The data structures that emerge out of that make sense as a developer and are aligned with their intended purposes. If people want a simple yes or no answer, they use singular checkboxes. If people want a list of items, they use multiselects. If we merge both as a single component, then it comes back to this argument: 

> The alternative of keeping them as a single component is a bit dodgy in my view because then we have one component which can be written in two formats. We also then need a few configuration fields on that component like (is multi checkbox) and (is dynamically loaded), which add a (I admit not huge) layer of having to dig through configuration to get the expected behavior.
