### ISSUE TITLE
Proper empty state

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#336]
> Quoting this from https://github.com/camunda/web-modeler/issues/2281

__Is your feature request related to a problem? Please describe__

As a user, I find it unclear how to build a form. There are no instructions on the empty state (white space) and no affordances such as open/close hand cursor or drag handle icons. My first assumption was to click on the tiles to add them.

![image](https://user-images.githubusercontent.com/56470362/191360970-a8e3ef57-7326-4f1a-a3ea-a5a4353e4d15.png)

__Describe the solution you'd like__

- Add some clear affordances that suggest dragging is possible

![image](https://user-images.githubusercontent.com/56470362/191361007-810225c9-d7b1-4c4d-a0ab-14b4262aec40.png)- 

![image](https://user-images.githubusercontent.com/56470362/191361074-695b3b10-deb2-4806-b975-1a17e1d70404.png)

- Support 'click to add' if drag is unclear for the majority users

__Describe alternatives you've considered__

Make use of the empty state

__Additional context__

- https://uxdesign.cc/drag-and-drop-for-design-systems-8d40502eb26d
- https://www.nngroup.com/articles/drag-drop/

**Comment by christian-konrad** [comment]
I would rather suggest us to add a empty state on the white-space in case the form is empty with a clear call-to-action: "Start building your form by dragging a component here from the palette"

**Comment by nikku** [comment]
We could take our (fairly well done) properties panel multi-select marker as an inspiration:

![image](https://user-images.githubusercontent.com/58601/191845060-be9d2859-19b2-45bc-ac40-3598ed5e3191.png)


@YanaSegal If you have a few minutes to sketch something (image to be accompained by text we craft) then we can incorporate that in no time. It would benefit the core toolkit, but also our apps UX.

**Comment by YanaSegal** [comment]
Hi, attached is the design for the empty state. It is based on the carbon design system and will be the cross-platform pattern for all empty states. 

![form-empty-state](https://user-images.githubusercontent.com/110401507/193762666-97275bd4-0e6b-4b26-9a02-f4426f07a1c1.png)

link to figma:
https://www.figma.com/file/iAXrTLUu6M7Cde4VfaShVY/Empty-states-%3E%3E-design-team?node-id=157%3A9088

SVG:
![forms_emptystate-icon](https://user-images.githubusercontent.com/110401507/193764172-6074da90-d61b-48ba-8c19-6029e7824ef6.svg)

**Comment by nikku** [comment]
To be done: 

* Verify https://github.com/bpmn-io/form-js/issues/336#issuecomment-1266541099 also works in Desktop Modeler / playground 
* To discuss (maybe @pinussilvestrus and @YanaSegal): Colors or no colors. We did settle in the past on minimum amount of colors and we're introducing a new one now.

**Comment by pinussilvestrus** [comment]
> * Verify [Proper empty state #336 (comment)](https://github.com/bpmn-io/form-js/issues/336#issuecomment-1266541099) also works in Desktop Modeler / playground

I can pretty much imagine that - I quickly sketched it below. The only thing we'd need to consider: should the preview also have a reasonable empty state or is the hint in the form definition enough (second screenshot)?

![Frame 1](https://user-images.githubusercontent.com/9433996/193818205-8e85cc05-dc17-4f3e-9b61-ed77437b8b0c.png)

![Frame 2](https://user-images.githubusercontent.com/9433996/193818246-fc0b84bf-2607-4419-ba74-bec76360d09d.png)

> To discuss (maybe @pinussilvestrus and @YanaSegal): Colors or no colors. We did settle in the past on minimum amount of colors and we're introducing a new one now.

My personal opinion (given the screenshots above): the orange stands out pretty much in comparison to the rest of the Desktop Modeler color palette. I understand we need to introduce a bit more color due to the Carbon introduction, but in the _current_ UI, I don't know whether we need it already. 

We also have to see that this empty state will be part of the `form-js` open source library and any additional color is something that our users immediately want to change - as it does not fit their design. 

We should have a good default (maybe grey, as @nikku suggested) and make it themeable via CSS variable. That's how we do it most of the time.

**Comment by pinussilvestrus** [comment]
@RomanKostka just saw this is still in ready. Do you have any plans to follow up? If not, let's move this to the backlog 👍

**Comment by YanaSegal** [comment]
@roman, that was a quick solution for the onboarding team. If you have the capacity, I think we can have a better empty state that hints that this is a drag-and-drop area, for example, a dashed frame. Feel free to change this design if you have a good solution :)

**Comment by Skaiir** [comment]
@RomanKostka Hey this will look very nice as an improvement, think we can resurrect the topic? Let me know if you've got the capacity for this one, and I'll implement it promptly.

If we're going for a dashed frame, it may make more sense for this to be implemented as a css border, as we'd ideally want it to scale with the window width I think. Let me know your thoughts.

**Comment by Skaiir** [comment]
Empty state images are available here ([internal](https://www.figma.com/file/iAXrTLUu6M7Cde4VfaShVY/Empty-states?node-id=728%3A13385&t=22aJDWGx5pFL2Vgg-1)).

Removed the `good first issue` tag from this one as it was less simple than initially expected. Will revisit this in the future, but if you want to try and tackle it, give us a shout.
