### ISSUE TITLE
[component]: Colored Boxes

### ISSUE THREAD

**Issue by jonathanlukas** [bpmn-io/form-js#642]
### Is your feature request related to a problem? Please describe.

When designing a form, it can be helpful to style sections using colored boxes.

### Describe the solution you'd like

The box should have configurable height and a color picker that allows a color pallet but also usage of color codes directly.

### Describe alternatives you've considered

Currently, all style attributes are filtered out from the HTML elements in the text view, so colored elements cannot be created.

### Additional context

https://camunda.slack.com/archives/C043W5V88M7/p1683112356908799

**Comment by Skaiir** [comment]
So, the approach of whitelisting styles is definitely a security risk, there are attacks based on style injection that could cause troubles. The problem comes when combining feelers with styles, a user could in theory try an attack which would involve them using CSS injection to get data from a tasklist user. It would be hard to do, but possible. 

See: https://stackoverflow.com/questions/41925390/what-are-the-risks-associated-with-using-inline-styles

This is only a problem if feelers is enabled though, so that means we wouldn't have to worry about this for non-expression evaluation. This is an approach we could take, another would be to have a dedicated component for this, or allow the spacer to be colored in for this, or have a separate component altogether. Something worth discussing further.

**Comment by christian-konrad** [comment]
@Skaiir couldn't we just make subforms colorable?

**Comment by Skaiir** [comment]
@christian-konrad Well I mean, I guess, but also then it becomes a styling component, and it becomes less focused. Also, we'd need to have a minimum height as well for it.
