### ISSUE TITLE
Saturday is not visible in the calendar view of the datepicker

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#788]
### Describe the Bug

When opening the calendar view of the datepicker the column for Saturdays is not visible:
![image](https://github.com/bpmn-io/form-js/assets/1022916/6227ebb5-d095-4b9b-a64f-fd187c1b5a70)

### Steps to Reproduce

1. Model a form with a datepicker
2. Open the calendar in the preview
3. The Saturday column is not visible

### Expected Behavior

The calendar column should be visible

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by pinussilvestrus** [comment]
@marcellobarile @vpellegrino The issue here comes from the styles set up in the Web Modeler. Let me specify

![image](https://github.com/bpmn-io/form-js/assets/9433996/ed45a77c-dceb-4d7c-94f6-0cefb888c9a4)

* We [export a `form-js.css` that bundles](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/assets/index.scss)
  * form-js-base styles (_that also include custom flatpickr styles_)
  * flatpickr light theme styles
  * Carbon grid
* The Web Modeler is [importing the bundled styles](https://github.com/camunda/web-modeler/blob/main/webapp/src/styles/modeling.scss#L9)
* The Web Modeler [imports the Carbon react styles](https://github.com/camunda/web-modeler/blob/main/webapp/src/styles/_carbon.scss), that _also include custom flatpickr styles_

=> These flatpickr styles clash that results in the issue above (and potentially more)

What we could do to mitigate that

* A) We keep the flatpickr customization out of form-js-base + Web Modeler uses `@camunda/form-playground/dist/assets/form-js-base.css`
* B) The Web Modeler finds a way to not import the Carbon flatpickr styles

Option A) is something [we already do in Tasklist](https://github.com/camunda/tasklist/blob/master/client/src/modules/components/FormJSRenderer/index.tsx#L12) to avoid styling clashes of the Carbon grid. 

What approach would you prefer?

**Comment by pinussilvestrus** [comment]
> We keep the flatpickr customization out of form-js-base + Web Modeler uses @camunda/form-playground/dist/assets/form-js-base.css

Independent from what we end up doing, making sure we keep the base styles _really basic_ is something we should consider (and we already sketched via #789)

**Comment by vpellegrino** [comment]
Hi @pinussilvestrus,
@marcellobarile and I had briefly discussed it, and we agree that approach A) would be preferred.

If you feel confident, you can open a PR on the [web-modeler](https://github.com/camunda/web-modeler) repository. Probably, [this is the file](https://github.com/camunda/web-modeler/blob/main/webapp/src/styles/modeling.scss#L5-L13) you are looking for, where we are already managing CSS file imports to avoid flushing.
If not, you can trace a GH issue and link it here.

**Comment by pinussilvestrus** [comment]
@vpellegrino thanks for confirming! I will definitely try to contribute a fix 👍 

Can you maybe give me access to the [test user credentials](https://reimagined-doodle-12d70320.pages.github.io/Product-Specific/Camunda-8-Web-Modeler/Development/Getting-Started-Development-Documentation/#test-users) so I can try it out locally?

**Comment by vpellegrino** [comment]
@pinussilvestrus, your camunda credentials (camunda email + SSO) should be enough for accessing the application locally. Please give it a try; if it does not work, we can find a different solution for sure. :)

**Comment by pinussilvestrus** [comment]
I suggested a fix upstream: https://github.com/camunda/web-modeler/pull/6180 (cf. rationale in the PR)
