### ISSUE TITLE
Components with complex conditions create a variable with null name in getSchemaVariables

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#860]
### Describe the Bug

Components with complex conditions create a variable with null name in getSchemaVariables.
The conditions must use a context in order to cause that behavior, like

```
{
  remainingAllowance: loanOptions.maxAllowance - loanOptions.currentlyUsed,
  restAfterNewLoan: remainingAllowance - offeredAdditionalLoan
}.restAfterNewLoan < 0
```

### Steps to Reproduce

1. Add a component
2. Add a complex condition that utilizes a context
3. Use it in Tasklist - it will break variables/search as getSchemaVariables outputs a variable with name `null`

<img width="1619" alt="image" src="https://github.com/bpmn-io/form-js/assets/56470362/1925f7a1-d744-40bc-ab62-e8adc99b28ae">

<img width="837" alt="image" src="https://github.com/bpmn-io/form-js/assets/56470362/f8b46e9c-c01a-4648-b4c3-d12dffc9a2a4">

![image](https://github.com/bpmn-io/form-js/assets/56470362/00b304ca-20d4-4129-b992-ad9303bea51b)

### Expected Behavior

* A group with empty path does not create a `null`entry in getSchemaVariables
* The list is sanitized by removing all `null` values
* Ideally, backend also ignores `null`s

### Environment

Form Editor in Web Modeler SaaS as of Oct 21 2023

**Comment by pinussilvestrus** [comment]
In form-js we filter for null values in the getSchemaVariables: https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/util/index.js#L179

We added that filter because we had a similar error in the past. It could be that we do this check too early though.

**Comment by Skaiir** [comment]
Issue is a few things.

First, my safeguard against null variables doesn't work because `if (not null or not undef)` is the same thing as `if(true)` (whoopsie).

Secondly, the null arises from the fact that we have this whole complex object structure stuff going on. Basically, {}.something is being treated as unnamed.something. The unnamed becomes null down the line. We should filter those out. 

Additionally we don't parse the internal scope of the object properly. This isn't a bug right now but will become one if we ever use a complex condition like that which doesn't rely on variables bound to keys.

So yeah, I'll fix things. Fixing the null situation is pretty trivial but I'll try and go for a full solution.
