### ISSUE TITLE
Group `path` is not merging variables across forms

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#913]
### Describe the Bug

Cf. this [support case](https://jira.camunda.com/browse/SUPPORT-19373)

Using a nested variable in various forms seems not to properly merge.

Given the following scenario: I have three forms after each other in a single process (three distinct user tasks) that all access to the same `user` object.

- Enter name
- Enter age
- Confirm both

<img width="720" alt="image" src="https://github.com/bpmn-io/form-js/assets/9433996/5b925db4-0a65-4bc5-9f3b-e1f43cdc891e">

<img width="770" alt="image" src="https://github.com/bpmn-io/form-js/assets/9433996/756b0228-8e32-4b1f-b8c7-687010d248e1">

<img width="751" alt="image" src="https://github.com/bpmn-io/form-js/assets/9433996/5551abcc-2c97-4b4f-b40f-9dfdfee25476">

<img width="749" alt="image" src="https://github.com/bpmn-io/form-js/assets/9433996/84c62136-b158-4ace-bef2-1461e718f322">

You can inspect in the third form that only the `age` is filled, `name` is empty.

<img width="860" alt="image" src="https://github.com/bpmn-io/form-js/assets/9433996/e2590752-7425-48fd-aaff-72b431a8b7bf">

### Steps to Reproduce

1. Create three forms as above
2. Embed all forms into a simple process
3. Deploy, start inspect the process on Tasklist
4. Fill first two forms after each other
5. See that `name` (user.name) is empty

### Expected Behavior

In the third step (confirm) both name and age should be displayed.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: macOS 13.6
- Library version: 1.4.0

**Comment by Skaiir** [comment]
Crux of the problem:

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/81255d74-e61e-4a09-8836-6570dcc4df06)

So, we've always sanitized out unused variables from the form schema, this made sense prior to objects because well, if the variable was not present in the output, then it simply would be ignored and not overwritten. But with objects now, this causes an issue, since we're not handling the variables in a truly hierarchical fashion outside of form-js, we simply replace one object with another, instead of merging recursively.

Here's how we could be merging it instead, https://stackoverflow.com/a/37164538.

Now, I'm actually not sure if we want to fix this **on form-js**. Because then we start becoming inconsistent in how we handle variables based on the level of nesting.

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/78dee644-9f35-4b69-99ee-44b6fe234e0c)

Root variables are never propagated to the output.

We could also just keep the input values, and return that + the true "output" deep merged on top. I'm uncertain whether this should be within or out of the library. 

@vsgoulart @nikku @pinussilvestrus @marstamm Opinions would be appreciated here, it's pretty badly breaking hence why I'm calling a lot of people out :D.

**Comment by marstamm** [comment]
I only briefly looked through the issue, but the merging should be done by the variable resolver on the bpmn level. It should not matter that the form only returns one property at a time. I'll have to take a closer look to understand what's happening

**Comment by marstamm** [comment]
I think I misunderstood the issue at first. Seems we have 2 things we need to tackle:

1. Execution
This seems to be the more critical one. The current behavior is unexpected, but not necessarily a form-js topic. IMO, as long as the API is clear (only submit what was changed) it is up to the integrating application (tasklist) to handle it in application-specific way. We should not make assumptions about the use-case in the library.
Tasklist would then handle merging of the variables before updating them in Zeebe.

2. Editor tooling
I checked editor tooling an `getSchemaVariables` does not return any nested variables, only root variable names. For better editor tooling in the modeler, it would be great to get the structure as well.
This is a feature request and is less urgent than the execution topic, I think

**Comment by Skaiir** [comment]
@marstamm Thank you for the input, I see it this way as well for the first point. For the second, I would definitely be up to provide a type definition with each variable, that's already a ticket but I guess it's worth emphasizing that it becomes more complicated now that we have nesting, will have a note there.

**Comment by Skaiir** [comment]
@vsgoulart Okay, good to hear you see it that way. So... okay I think personally option 1 is the better choice. I foresee users getting confused by this behavior of having to do the merge themselves, refer to the docs, find it there, waste some time and waste some support time too.

Implementing once on tasklist or every single one of our users implementing the merge every time they have to use nested objects from a UX perspective is an easy win for 1. Performance wise, how bad does it really get? I mean, I'm sure merges can get slow but like are we talking milliseconds? Because if so it's still pretty much nothing relative to the time of filling out a form. Also, the way I understand a deep merge working, its time complexity scales with the size of **one** of the two objects, and in the case of forms we will not be seeing 1000 property objects, so I really doubt this would be an issue.

@volodymyr-melnykc @christian-konrad Opinions?

**Comment by nikku** [comment]
> IMO, as long as the API is clear (only submit what was changed) it is up to the integrating application (tasklist) to handle it in application-specific way

This is the imporant part. Please keep contracts stable, i.e. also with nesting only submit what is present in the form at the time of submit.

> We do a deep merge of objects on Tasklist.

This is what I'd suggest us to do, mirroring @marstamm's and @Skaiir's prior comments. 

I cannot judge "internal tasklist merging" vs. engine output mapping merging, but to figure out what is best I'd take the users perspective. What would be least surprising and helpful to them, cf. [design principles](https://github.com/bpmn-io/design-principles)?

I do suggest to consider "performance implications of deep merge" an edge case :slightly_smiling_face:.

**Comment by volodymyr-melnykc** [comment]
Based on my understanding and keeping the end user in mind, doing the deep merge of objects is better.

> take the users perspective. What would be least surprising and helpful to them, cf. [design principles](https://github.com/bpmn-io/design-principles)? My slight tendency is to do the merging internally, offer the full "updated object", and allow users to extract partial results via output mappings, if desired.

👍

**Comment by tobiasschaefer** [comment]
I actually created the initial support issue and followed the link to this issue.

Thanks for tackling this use case. I agree to previous comments: from my perspective it would be perfect if the tasklist app did the deep merging of the two JSON objects when the "complete" API is called.

**Comment by vsgoulart** [comment]
I'm closing this issue in favor of an issue in the Tasklist repo

@tobiasschaefer if you want to follow progress in this you can check it [here](https://github.com/camunda/issues/issues/372)
