### ISSUE TITLE
Dynamic List - handle empty state better with resizing

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#965]
### Describe the Bug

When resizing the dynamic list to be very little, the empty state starts looking very messy, we should find an alternative to this, either by hiding the state entirely or substituting it for a smaller, simpler text field (or even just an icon). 

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/51d32930-6f64-4ac9-a111-d3833f53b8dc)

### Steps to Reproduce

1. Add a dynamic list
2. Make it 2 columns wide
3. The placeholder text renders poorly

### Expected Behavior

- Update the placeholder text from "_Drag and drop components here to create a repeatable list item_" to "_**Drag and drop components here.**_":
  - The updated placeholder text to be shown for wider breakpoints.
  - No need to mention in the placeholder text that components will be repeated since there is a separate indicator below.
- When the width of the Dynamic list component is less than 150px then the placeholder text is not displayed.

### Context

- follow-up from https://github.com/bpmn-io/form-js/issues/796

**Comment by volodymyr-melnykc** [comment]
I have a few suggestions here:

- Update the placeholder text to "_Drag and drop components here._" instead of "_Drag and drop components here to create a repeatable list item_":
  - The updated placeholder text to be shown for wider breakpoints
  - No need to mention in the placeholder text that components will be repeated since there is a separate indicator below.
- When the width of the Dynamic list component is less than 150px then the placeholder text is not displayed.

@Skaiir 

<img width="220" alt="image" src="https://github.com/bpmn-io/form-js/assets/143816833/0e003e3c-d449-4cd9-8de8-ca402e1f1cb0">
